services:
  api:
    build: .
    container_name: api
    ports:
      - "3000:3000"
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - bitcoin-hoje-network

  redis:
    image: redis:latest
    container_name: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    restart: unless-stopped
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      - bitcoin-hoje-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    restart: unless-stopped
    depends_on:
      - api
    networks:
      - bitcoin-hoje-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    restart: unless-stopped
    depends_on:
      - prometheus
    networks:
      - bitcoin-hoje-network
      
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
    - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    - /etc/letsencrypt/live/bitcoinhoje.site:/etc/letsencrypt/live/bitcoinhoje.site:ro
    - /etc/letsencrypt/archive/bitcoinhoje.site:/etc/letsencrypt/archive/bitcoinhoje.site:ro
    restart: unless-stopped
    depends_on:
      - api
    networks:
      - bitcoin-hoje-network

networks:
  bitcoin-hoje-network:
    external: true
